### ISSUE TITLE
[feat] hover memos command supporting auto-resize

### ISSUE THREAD

**Issue by edonyzpc** [edonyzpc/obsidian-plugins-mng#42]
### Requirement/Scenario
hover memos command will display hover editor view by default size which is to small or at wrong position. I hope the command can do auto-resize view after hover editor showup.

### Function
command hover editor support auto-resizing.

## Tasks
- [ ] abstract a class which is including memos
    - [ ] origin hover memos function
    - [ ] auto-resize function
